name: Build & Release Tauri App

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Node, Rust targets, etc.)
        run: |
          npm install
          cargo install tauri-cli
          rustup target add x86_64-unknown-linux-gnu

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf

      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install appiconutils

      - name: Build Tauri app
        run: |
          npm run tauri build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Tauri App
          path: src-tauri/target/release/bundle
