name: Tauri Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `${context.ref}`.replace('refs/tags/', ''),
              name: `${context.ref}`.replace('refs/tags/', ''),
              draft: true,
              prerelease: false
            });
            return data.id

  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - platform: macos-latest
            target: macos
          - platform: ubuntu-latest
            target: linux
          - platform: windows-latest
            target: windows

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libxdo-dev

      - name: Install frontend dependencies
        run: npm ci # or yarn install or pnpm install

      - name: Install imagemagick for icon conversion
        uses: mfinelli/setup-imagemagick@v1

      - name: Install png2icons for macOS icons
        if: matrix.platform == 'macos-latest'
        run: npm install -g png2icons

      - name: Generate app icons from PNG
        run: |
          mkdir -p src-tauri/icons/

          # Convert PNG to multiple resolutions
          convert icon.png -resize 32x32 src-tauri/icons/32x32.png
          convert icon.png -resize 128x128 src-tauri/icons/128x128.png
          convert icon.png -resize 256x256 src-tauri/icons/256x256.png
          convert icon.png -resize 512x512 src-tauri/icons/512x512.png
          convert icon.png -resize 1024x1024 src-tauri/icons/1024x1024.png

          # Generate Windows ICO file
          if [ "${{ matrix.platform }}" = "windows-latest" ]; then
            convert src-tauri/icons/32x32.png src-tauri/icons/128x128.png src-tauri/icons/256x256.png src-tauri/icons/icon.ico
          fi

          # Generate macOS ICNS file
          if [ "${{ matrix.platform }}" = "macos-latest" ]; then
            png2icons src-tauri/icons/1024x1024.png src-tauri/icons/icon -icns
          fi

          # Copy icon.png for Linux
          if [ "${{ matrix.platform }}" = "ubuntu-latest" ]; then
            cp src-tauri/icons/512x512.png src-tauri/icons/icon.png
          fi
        shell: bash

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}

  publish-release:
    runs-on: ubuntu-latest
    needs: [create-release, build-tauri]

    steps:
      - name: Publish release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false
            });
