name: Tauri Build and Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.result }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create release
        id: create-release
        uses: actions/github-script@v6
        with:
          script: |
            const { data } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `${context.ref}`.replace('refs/tags/', ''),
              name: `${context.ref}`.replace('refs/tags/', ''),
              draft: true,
              prerelease: false
            });
            return data.id

  build-tauri:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - platform: macos-latest
            target: macos
          - platform: ubuntu-latest
            target: linux
          - platform: windows-latest
            target: windows

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies (Linux only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libxdo-dev imagemagick

      - name: Install frontend dependencies
        run: npm ci

      # macOS 图标处理
      - name: Generate app icons for macOS
        if: matrix.platform == 'macos-latest'
        run: |
          brew install imagemagick
          mkdir -p src-tauri/icons/
          for size in 256 512 1024; do
            magick icon.png -resize ${size}x${size} -define png:color-type=6 src-tauri/icons/${size}x${size}.png
          done
          cp src-tauri/icons/256x256.png src-tauri/icons/128x128@2x.png
          cp src-tauri/icons/512x512.png src-tauri/icons/256x256@2x.png
          cp src-tauri/icons/1024x1024.png src-tauri/icons/512x512@2x.png
          magick src-tauri/icons/*.png src-tauri/icons/icon.icns

      # Linux 图标处理
      - name: Generate app icons for Linux
        if: matrix.platform == 'ubuntu-latest'
        run: |
          mkdir -p src-tauri/icons/
          for size in 256 512 1024; do
            convert icon.png -resize ${size}x${size} -define png:color-type=6 src-tauri/icons/${size}x${size}.png
          done
          # 模拟 @2x 图标（Tauri 需要）
          cp src-tauri/icons/256x256.png src-tauri/icons/128x128@2x.png
          cp src-tauri/icons/512x512.png src-tauri/icons/256x256@2x.png
          cp src-tauri/icons/1024x1024.png src-tauri/icons/512x512@2x.png
          # 设置主图标（非必须，但推荐）
          cp src-tauri/icons/512x512.png src-tauri/icons/icon.png
          # 生成 ico/icns（确保打包成功）
          convert src-tauri/icons/512x512.png src-tauri/icons/256x256.png src-tauri/icons/icon.ico
          cp src-tauri/icons/icon.png src-tauri/icons/icon.icns

      # Windows 图标处理
      - name: Generate app icons for Windows
        if: matrix.platform == 'windows-latest'
        run: |
          choco install imagemagick -y
          mkdir src-tauri/icons
          magick icon.png -resize 256x256 -define png:color-type=6 src-tauri/icons/256x256.png
          magick icon.png -resize 512x512 -define png:color-type=6 src-tauri/icons/512x512.png
          magick src-tauri/icons/512x512.png src-tauri/icons/256x256.png src-tauri/icons/icon.ico

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.release_id }}

  publish-release:
    runs-on: ubuntu-latest
    needs: [create-release, build-tauri]

    steps:
      - name: Publish release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            await github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false
            });
